name: Push to gh-pages

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v4.4.0

      - run: npm install

      - name: Gen Html
        run: node tools/md2html.js

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
