name: Push to gh-pages

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v4.4.0

      - run: npm install

      - name: Gen Html
        run: node tools/md2html.js

      - name: Push to branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/ docs/ CNAME index.html
          git commit -m "Automated commit" || echo "No changes"
          git push origin HEAD:gh-pages
